sudo: required
services:
  - docker

before_install:
  - docker build -t AlfiSoftware/docker-react -f Dockerfile.dev .

script:
  - docker run AlfiSoftware/docker-react npm run test -- --coverage